frr defaults traditional
hostname bottom
service integrated-vtysh-config
!
router bgp 65300
 bgp router-id 10.255.0.3
 no bgp ebgp-requires-policy
 neighbor 10.44.3.2 remote-as 65100
 neighbor 10.44.4.3 remote-as 65200
 address-family ipv4 unicast
  neighbor 10.44.3.2 activate
  neighbor 10.44.4.3 activate
 exit-address-family
!