frr defaults traditional
hostname right
service integrated-vtysh-config
!
router bgp 65200
 bgp router-id 10.255.0.4
 no bgp ebgp-requires-policy
 neighbor 10.44.2.2 remote-as 65000
 neighbor 10.44.4.2 remote-as 65300
 address-family ipv4 unicast
  network 10.52.0.0/24
  neighbor 10.44.2.2 activate
  neighbor 10.44.4.2 activate
 exit-address-family
!