frr defaults traditional
hostname top
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor 10.44.1.2 remote-as 65100
 neighbor 10.44.2.3 remote-as 65200
 address-family ipv4 unicast
  neighbor 10.44.1.2 activate
  neighbor 10.44.2.3 activate
 exit-address-family
!